name = input("Enter youe full name:")
phoneNumber = input("Enter your phone number #: ")
result = len(name)
result = name.find("O")
result = name.rfind("q")
name = name.capitalize()
name = name.upper()
name = name.lower()
result = name.isdigit()
result = name.isalpha()
result = phoneNumber.count("-")
result = phoneNumber.replace("-","")
result = phoneNumber[::-1]
print(result)